# AR parameters such as FFT parameters.
audio_repr: ar_whisper.AR_Whisper
feature_d: 1280
sample_rate: 16000
temporal_pooling_type: mean

# Training parameters.
batch_size: 64
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20

# Model specific parameters.
pretrained_model: openai/whisper-large-v3

output_layers: [-1]  # list of layers to stack
